version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  django:
    build: ./backend_api
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend_api:/app/backend_api
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./frontend_ui
    command: ["npm", "start"]
    volumes:
      - ./frontend_ui:/app/frontend_ui
      - node-modules:/app/frontend_ui/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules:
